# Generated by Django 5.2.4 on 2026-06-07 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_alter_project_created_at_and_more"),
        ("users", "0002_user_favorites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Название технологии"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(
                blank=True, max_length=256, verbose_name="Описание профиля / О себе"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="Аватарка"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_users",
                to="projects.project",
                verbose_name="Избранные проекты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на GitHub"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный аккаунт"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="Доступ к админ-панели"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=124, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.skill",
                verbose_name="Навыки",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=124, verbose_name="Фамилия"),
        ),
    ]
