USER_NAME_MAX_LEN = 124
USER_SURNAME_MAX_LEN = 124
USER_PHONE_MAX_LEN = 12
USER_ABOUT_MAX_LEN = 256
PROJECT_NAME_MAX_LEN = 200
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
]
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
AVATAR_COLORS = [
    "#FFB3BA",
    "#FFDFBA",
    "#FFFFBA",
    "#BAFFC9",
    "#BAE1FF",
    "#E2CBF7",
    "#D5E8D4",
]
AVATAR_TEXT_COLOR = "#333333"
AVATAR_SIZE = (200, 200)
AVATAR_FONT_SIZE = 100
AVATAR_DEFAULT_LETTER = "U"
AVATAR_FONT_NAME = "arial.ttf"

PROJECT_STATUS_MAX_LEN = max(len(status) for status, _ in PROJECT_STATUS_CHOICES)
